###################################################
# +---------------------------------------------+ #
# |             Database Connection             | #
# +---------------------------------------------+ #
###################################################

# CAUTION! Developer mode will drop all database tables on startup. DO NOT USE IN PRODUCTION.
developer-mode: false

# Database connection settings.
mysql:
  host: localhost
  port: 3306
  username: unitedpolitics
  password: unitedpolitics
  database: unitedpolitics

###################################################
# +---------------------------------------------+ #
# |              New Day Scheduling             | #
# +---------------------------------------------+ #
###################################################

# How long a day lasts (in real time) until reputation decay is applies. Can't be more than 
# 24 real-life hours or less than 1 real-life minute. Use d, h, m and s as units.
new-day-interval: 1d
# If the new day interval is 1d, this is the hour of the day (UTC) at which the new day is started.
# If the interval is less than 1d, this option is ignored and the interval is started from the last
# reboot of the server.
# Must be a number between 0 and 23.
new-day-start-hour: 12


###################################################
# +---------------------------------------------+ #
# |   Settings for reputation actions & events  | #
# +---------------------------------------------+ #
###################################################

# Whether reputation changes on one level will also change reputation on higher or lower levels.
# Each consecutive level will be multiplied by the factor. Example: with upward passthrough of 0.5,
# a town reputation change of +10 will propagate to +5 for the region and +2.5 for the nation.
# With downward passthrough of 0.1, a nation reputation change of -50 will propagate to -5 for
# all regions and -0.5 for all towns.
rep-passthrough-up:
  enabled: true
  factor: 0.5
rep-passthrough-down:
  enabled: true
  factor: 0.5
# The time period after the last change in a reputation sore in which the score will not be
# subject to daily decay (in seconds). Should be be more than a day to be effective.
rep-decay-grace-period: 259200

settings:
  # Paying tribute to a town, region or nation
  tribute:
    # How much reputation will be given per unit of currency (default: 1 for 10,000)
    reputationPerMoneyUnit: 0.0001
    # If supported, log entry messages for the economy plugin
    moneyLogReasonSource: "Paid tribute to "
    moneyLogReasonTarget: "Tribute paid by "

  # Killing an player of a different town
  killed:
    # Should deaths change reputation
    enabled: true
    # Ignore deaths in these worlds
    blacklisted-worlds:
      - sample_world
    # Amount of reputation loss for the kill
    amount: -5

  # ************
  # Integrations
  # ************

  # Towny
  townscreen:
    enabled: true
    after-component: "founder"
    content-observer: "<dark_green>Their opinion of us: {score}"
    content-subject: "<dark_green>Our opinion of them: {score}"
    details: "<dark_green>Click for more information</dark_green>"
  nationscreen:
    enabled: true
    after-component: "capital"
    content-observer: "<dark_green>Their opinion of us: {score}"
    content-subject: "<dark_green>Our opinion of them: {score}"
    details: "<dark_green>Click for more information</dark_green>"

  # UnitedTrade
  ut-trade-complete:
    # Give extra money for high reputation
    reputation-bonus:
      enabled: true
      # The minumum reputation to receive a bonus
      minimum: 50
      # The reputation above which the bonus is not scaled anymore
      limit: 100
      # The multiplier
      # Example: With minmum 50 and limit 100, at a reputation of 75, the bonus
      # will be 0.5 (75 is halfway between 50 and 100) * 0.5 (factor) = 0.25, so
      # an additional 25% of of the original payment.  At 100 reputation, the
      # bonus will be 1 * 0.5 = 0.5, so an additonal 50%.
      factor: 0.5
      # The reason that will be displayed to the player
      reason: "High reputation with the trader"

  # UnitedWar
  uw-warred-us:
    enabled: true
    # In nation wars, this penalty is applied to the defending nation (and towns if passthrough-down is enabled).
    # In town wars, this penalty is applied to the defending town.
    amount: -200
  # Reputation penalty for warring a town that someone is friends with
  uw-warred-friend:
    enabled: true
    # The reputation needed for a town to be considered a friend
    threshold: 100
    # The penalty
    amount: -100
  # Reputation penalty for warring a town that someone is enemies with
  uw-warred-enemy:
    enabled: true
    # The reputation needed for a town to be considered an enemy
    threshold: -100
    # The bonus
    amount: 100

  # UnitedDungeons
  ud-looted-hostile-dungeon:
    # The penalty
    amount: 5
  ud-looted-friendly-dungeon:
    # The penalty
    amount: -5

# +---------------------------------------------+ #
# |            Default event keys               | #
# +---------------------------------------------+ #

event-keys:
  - PAID_TRIBUTE
  - KILLED_PLAYER
  - TRADE_COMPLETE
  - TRADE_FAILED
  - WAR_DECLARED

# +---------------------------------------------+ #
# |       Special integration mechanics         | #
# +---------------------------------------------+ #

integration-mechanics:
  UnitedTrade:
    # Disallow picking up trade orders if reputation with NPC town is below minimum defined by the trade point
    use-minimum-town-reputation: true
    # Disallow picking up trade orders if reputation with NPC nation is below minimum defined by the trade point
    use-minimum-nation-reputation: true
    # The default reputation that a player has if their reputation can't be calculated (e.g. when they're townless)
    default-reputation: 0
    minimum-fail-message: "<red>You can't use this, your reputation with {name} is too low (needs to be at least {minimum}).</red>"
